version: '3.8'
services:
  postgres:
    image: "postgres:14"
    container_name: "adminer_historico_postgres"  # Nome do container do PostgreSQL
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"  # Porta do PostgreSQL
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  historico-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: historico_service_container
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://adminer_historico_postgres:5432/postgres  # Atualizar URL com o novo nome do banco
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: create
    depends_on:
      - postgres
    ports:
      - "8086:8086"  # Porta do serviço historico
    networks:
      - app_network

  adminer:
    image: adminer
    container_name: adminer_historico_novo  # Novo nome para evitar conflito
    depends_on:
      - postgres
    ports:
      - "8282:8080"  # Nova porta mapeada para o Adminer
    networks:
      - app_network

networks:
  app_network:

volumes:
  postgres_data: