version: '3.8'
services:
  postgres:
    image: "postgres:14"
    container_name: "postgres"  # Nome do container do PostgreSQL
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"  # Porta do PostgreSQL
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - projetos-fiap-2025-hospitalar-historico_app_network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest  # Usando a imagem do Confluent
    container_name: zookeeper
    restart: always
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - projetos-fiap-2025-hospitalar-historico_app_network
  kafka:
    build:
      context: .
      dockerfile: Dockerfile.kafka
    container_name: kafka
    restart: always
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:29092  # Alteração: Adicionado OUTSIDE para acesso externo
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT  # Alteração: Mapeamento de protocolos
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:29092  # Alteração: Configuração dos listeners
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "consultas-agendadas:1:1"
    ports:
      - "9092:9092"
      - "29092:29092"  # Alteração: Porta para acesso externo
    depends_on:
      - zookeeper  # Alteração: Garantir que Kafka inicie após Zookeeper
    networks:
      - projetos-fiap-2025-hospitalar-historico_app_network

  historico-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: historico_service_container
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: create
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - postgres
      - kafka
    ports:
      - "8086:8086"  # Porta do serviço historico
    networks:
      - projetos-fiap-2025-hospitalar-historico_app_network

  adminer:
    image: adminer
    container_name: adminer  # Novo nome para evitar conflito
    depends_on:
      - postgres
    ports:
      - "8282:8080"  # Nova porta mapeada para o Adminer
    networks:
      - projetos-fiap-2025-hospitalar-historico_app_network

networks:
  projetos-fiap-2025-hospitalar-historico_app_network:


volumes:
  postgres_data: